FROM node:18-alpine

WORKDIR /app

RUN npm install -g typescript

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx tsc

RUN npm prune --production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nestjs -u 1001

RUN chown -R nestjs:nodejs /app
USER nestjs

EXPOSE 3000

CMD ["node", "dist/src/main.js"] 