version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chat_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_app
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: chat_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chat_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: production
    container_name: chat_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=chat_user
      - DB_PASSWORD=chat_password
      - DB_DATABASE=chat_app
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_LAMBDA_FUNCTION_NAME=${AWS_LAMBDA_FUNCTION_NAME:-message-processor}
    depends_on:
      - mysql
    networks:
      - chat_network

volumes:
  mysql_data:

networks:
  chat_network:
    driver: bridge 