services:
  - type: web
    name: chat-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: 3306
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: chat-database
    databaseName: chat_app
    user: chat_user 