name: chat-app
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/chat-app
      branch: main
    run_command: npm run start:prod
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_HOST}
      - key: DATABASE_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_PORT}
      - key: DATABASE_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_USERNAME}
      - key: DATABASE_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_PASSWORD}
      - key: DATABASE_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_NAME}

databases:
  - name: db
    engine: mysql
    version: "8" 